version: '3.8'

services:
  app:
    container_name: elloms-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - app-data:/app/data  
    networks:
      - app-network

volumes:
  app-data:
    driver: local

networks:
  app-network:
    driver: bridge 